//! The clipboard: a history of what you copied (opt-in, Mac control) and the
//! reads/writes the selection hotkey needs (selection.rs).
//!
//! Privacy first:
//! - History is off until the user switches it on (Settings → Features).
//! - Anything a password manager marks as secret (the nspasteboard.org
//!   "concealed" and "transient" types) is never kept, and neither is text that
//!   looks like a password or API key.
//! - It's stored in the encrypted database, at most 200 items, text only, and can
//!   be cleared at any time. What BYTE itself puts on the clipboard isn't recorded.

use serde::Serialize;
use tauri::{Manager, State};

use crate::error::AppResult;
use crate::state::AppState;

/// Items kept.
const KEEP: i64 = 200;
/// Longest item kept (characters).
const MAX_CHARS: usize = 20_000;

/// Pasteboard types that mean "don't record this" (nspasteboard.org and apps
/// that predate it).
#[cfg_attr(not(target_os = "macos"), allow(dead_code))]
pub const SECRET_TYPES: &[&str] = &[
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
    "com.agilebits.onepassword",
    "de.petermaurer.TransientPasteboardType",
    "Pasteboard generator type",
];

/// Text that looks like a password, token or key: one "word", fairly long, with
/// a mix of character kinds (or a well-known key prefix). Kept out of history.
pub fn looks_secret(text: &str) -> bool {
    let t = text.trim();
    if t.contains(char::is_whitespace) || t.len() < 10 || t.len() > 300 {
        return false;
    }
    const PREFIXES: &[&str] = &["sk-", "sk_", "pk_", "rk_", "ghp_", "gho_", "github_pat_", "xox", "AKIA", "AIza", "byte_", "glpat-", "eyJ"];
    if PREFIXES.iter().any(|p| t.starts_with(p)) {
        return true;
    }
    if t.starts_with("http://") || t.starts_with("https://") || t.contains('@') && t.contains('.') && !t.contains(':') {
        return false;
    }
    let kinds = [t.chars().any(|c| c.is_ascii_lowercase()), t.chars().any(|c| c.is_ascii_uppercase()), t.chars().any(|c| c.is_ascii_digit()), t.chars().any(|c| !c.is_alphanumeric())];
    kinds.iter().filter(|k| **k).count() >= 3 && t.len() <= 128
}

/// Whether a copied text should be kept in the history.
pub fn keep(text: &str, secret_type: bool) -> bool {
    let t = text.trim();
    !secret_type && !t.is_empty() && t.chars().count() <= MAX_CHARS && !looks_secret(t)
}

// ---------------------------------------------------------------- the board

/// The system clipboard (macOS NSPasteboard). Elsewhere: nothing.
#[cfg(target_os = "macos")]
pub mod board {
    use objc2_app_kit::{NSPasteboard, NSPasteboardTypeString};
    use objc2_foundation::NSString;

    /// Changes each time anything is copied.
    pub fn change_count() -> i64 {
        objc2::rc::autoreleasepool(|_| NSPasteboard::generalPasteboard().changeCount() as i64)
    }

    /// The copied text, if there is any.
    pub fn text() -> Option<String> {
        objc2::rc::autoreleasepool(|_| {
            let pb = NSPasteboard::generalPasteboard();
            // SAFETY: NSPasteboardTypeString is an immutable AppKit constant.
            let t = unsafe { NSPasteboardTypeString };
            pb.stringForType(t).map(|s| s.to_string())
        })
    }

    /// A password manager marked the copied item as secret.
    pub fn secret() -> bool {
        objc2::rc::autoreleasepool(|_| {
            let pb = NSPasteboard::generalPasteboard();
            pb.types().map(|ts| ts.iter().any(|t| super::SECRET_TYPES.contains(&t.to_string().as_str()))).unwrap_or(false)
        })
    }

    /// Puts text on the clipboard; returns the new change count.
    pub fn set_text(text: &str) -> i64 {
        objc2::rc::autoreleasepool(|_| {
            let pb = NSPasteboard::generalPasteboard();
            pb.clearContents();
            // SAFETY: as above.
            let t = unsafe { NSPasteboardTypeString };
            pb.setString_forType(&NSString::from_str(text), t);
            pb.changeCount() as i64
        })
    }
}

#[cfg(not(target_os = "macos"))]
pub mod board {
    pub fn change_count() -> i64 {
        0
    }
    pub fn text() -> Option<String> {
        None
    }
    pub fn secret() -> bool {
        false
    }
    pub fn set_text(_text: &str) -> i64 {
        0
    }
}

/// The change count of BYTE's own last write, so it isn't recorded.
static OWN_WRITE: std::sync::atomic::AtomicI64 = std::sync::atomic::AtomicI64::new(-1);

/// Puts text on the clipboard without it showing up in the history.
pub fn set_quietly(text: &str) {
    let n = board::set_text(text);
    OWN_WRITE.store(n, std::sync::atomic::Ordering::SeqCst);
}

// ------------------------------------------------------------------ history

#[derive(Debug, Clone, Serialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct Clip {
    pub id: i64,
    pub text: String,
    /// When it was copied (ms since 1970).
    pub at: i64,
}

/// Adds a copied text (the same text again just moves to the top); keeps 200.
pub fn add(db: &crate::db::Db, text: &str, at: i64) -> AppResult<()> {
    let conn = db.conn();
    conn.execute("DELETE FROM clip_history WHERE text = ?1", [text])?;
    conn.execute("INSERT INTO clip_history (text, at) VALUES (?1, ?2)", rusqlite::params![text, at])?;
    conn.execute("DELETE FROM clip_history WHERE id NOT IN (SELECT id FROM clip_history ORDER BY at DESC, id DESC LIMIT ?1)", [KEEP])?;
    Ok(())
}

/// Newest first; `query` filters by the words in it (case-insensitive).
pub fn list(db: &crate::db::Db, query: &str) -> AppResult<Vec<Clip>> {
    let conn = db.conn();
    let like = format!("%{}%", query.trim().replace('\\', "\\\\").replace('%', "\\%").replace('_', "\\_"));
    let mut st = conn.prepare("SELECT id, text, at FROM clip_history WHERE text LIKE ?1 ESCAPE '\\' ORDER BY at DESC, id DESC LIMIT ?2")?;
    let rows = st.query_map(rusqlite::params![like, KEEP], |r| Ok(Clip { id: r.get(0)?, text: r.get(1)?, at: r.get(2)? }))?;
    Ok(rows.collect::<Result<_, _>>()?)
}

pub fn delete(db: &crate::db::Db, id: i64) -> AppResult<()> {
    db.conn().execute("DELETE FROM clip_history WHERE id = ?1", [id])?;
    Ok(())
}

pub fn clear(db: &crate::db::Db) -> AppResult<()> {
    db.conn().execute("DELETE FROM clip_history", [])?;
    Ok(())
}

/// Watches the clipboard once a second while history is on (macOS).
pub fn watch(app: tauri::AppHandle) {
    if !cfg!(target_os = "macos") {
        return;
    }
    tauri::async_runtime::spawn(async move {
        let mut last = board::change_count();
        loop {
            tokio::time::sleep(std::time::Duration::from_millis(1000)).await;
            let state = app.state::<AppState>();
            if !state.settings.lock().await.clipboard_history {
                last = board::change_count();
                continue;
            }
            let now = board::change_count();
            if now == last {
                continue;
            }
            last = now;
            if now == OWN_WRITE.load(std::sync::atomic::Ordering::SeqCst) {
                continue;
            }
            let secret = board::secret();
            if let Some(text) = board::text() {
                if keep(&text, secret) {
                    if let Err(e) = add(&state.db, &text, chrono::Utc::now().timestamp_millis()) {
                        log::warn!("clipboard history: {e}");
                    }
                }
            }
        }
    });
}

#[tauri::command]
pub fn clip_list(state: State<'_, AppState>, query: Option<String>) -> AppResult<Vec<Clip>> {
    crate::lock::ensure(&state)?;
    crate::kids::grownups_only()?;
    list(&state.db, query.as_deref().unwrap_or(""))
}

/// Copies an item back to the clipboard (it moves to the top).
#[tauri::command]
pub fn clip_copy(state: State<'_, AppState>, id: i64) -> AppResult<()> {
    let text: Option<String> = {
        use rusqlite::OptionalExtension;
        state.db.conn().query_row("SELECT text FROM clip_history WHERE id = ?1", [id], |r| r.get(0)).optional()?
    };
    if let Some(t) = text {
        set_quietly(&t);
        add(&state.db, &t, chrono::Utc::now().timestamp_millis())?;
    }
    Ok(())
}

#[tauri::command]
pub fn clip_delete(state: State<'_, AppState>, id: i64) -> AppResult<()> {
    delete(&state.db, id)
}

#[tauri::command]
pub fn clip_clear(state: State<'_, AppState>) -> AppResult<()> {
    clear(&state.db)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn secrets_are_never_kept() {
        for s in ["hunter2Pass!", "Tr0ub4dor&3xyz", "sk-proj-abc123def456", "ghp_TESTexample12345", "eyJhbGciOiJIUzI1NiJ9.e30.abc", "byte_test_1234567890"] {
            assert!(looks_secret(s), "{s}");
            assert!(!keep(s, false), "{s}");
        }
        for s in ["Meeting moved to Thursday at 10", "https://example.com/a?b=C1&d=2", "sam@example.com", "gate code 4417", "Hello", "fn main() { println!(\"hi\"); }"] {
            assert!(!looks_secret(s), "{s}");
            assert!(keep(s, false), "{s}");
        }
        assert!(!keep("ordinary text", true), "marked secret by a password manager");
        assert!(!keep("   ", false));
        assert!(!keep(&"x".repeat(MAX_CHARS + 1), false));
    }

    #[test]
    fn history_keeps_200_newest_without_repeats() {
        let dir = tempfile::tempdir().unwrap();
        let db = crate::db::Db::open(dir.path()).unwrap();
        for i in 0..205 {
            add(&db, &format!("item {i}"), i).unwrap();
        }
        let all = list(&db, "").unwrap();
        assert_eq!(all.len(), 200);
        assert_eq!(all[0].text, "item 204");
        assert!(!all.iter().any(|c| c.text == "item 4"), "the oldest went");
        add(&db, "item 100", 1000).unwrap();
        let all = list(&db, "").unwrap();
        assert_eq!((all.len(), all[0].text.as_str()), (200, "item 100"), "copying again moves it up, no duplicate");
        assert_eq!(list(&db, "ITEM 20").unwrap().iter().map(|c| c.text.as_str()).collect::<Vec<_>>(), ["item 204", "item 203", "item 202", "item 201", "item 200", "item 20"]);
        assert!(list(&db, "100%").unwrap().is_empty(), "% is literal");
        delete(&db, all[0].id).unwrap();
        assert_eq!(list(&db, "").unwrap().len(), 199);
        clear(&db).unwrap();
        assert!(list(&db, "").unwrap().is_empty());
    }
}
